services:
  - type: web
    name: swiggy-fyi
    env: static
    buildCommand: cd react-app && npm install && npm run build
    staticPublishPath: ./react-app/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
